spring:
  application:
    name: iecommerce
  config:
    import: vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${SPRING_CLOUD_VAULT_TOKEN:root}
      kv:
        enabled: true
        backend: secret
        default-context: iecommerce
        application-name: iecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/iecommerce
    username: ${postgres.username:admin}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.server-url}/realms/${app.keycloak.realm}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mail:
    host: localhost
    port: 1025 # MailHog or similar dummy SMTP server

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true

server:
  port: 8081
  error:
    whitelabel:
      enabled: false  # Use our custom Thymeleaf error pages



app:
  keycloak:
    server-url: http://localhost:8080
    realm: iecommerce
    admin:
      username: admin
      password: ${keycloak.admin.password:admin}
      client-id: admin-cli
    clients:
      web: iecommerce-web-client
      admin: iecommerce-admin-client

  kong:
    admin-url: http://localhost:8001
    upstream-url: http://host.docker.internal:8081

logging:
  level:
    org.springframework.modulith: INFO
    com.chamrong: DEBUG
iecommerce:
  storage:
    r2:
      endpoint: https://dummy.r2.cloudflarestorage.com
      accessKey: dummy
      secretKey: dummy
      bucketName: iecommerce-bucket
      publicUrl: https://cdn.dummy.com

  twilio:
    accountSid: dummy_sid
    authToken: dummy_token
    systemPhoneNumber: "+15555555555"

