spring:
  application:
    name: iecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/iecommerce
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true

server:
  port: 8080

logging:
  level:
    org.springframework.modulith: INFO
    com.chamrong: DEBUG
